const team = [{name: "Nicola",
    surname: "Pisani",
    age: "24",
    city: "Potenza",
    hobby: "Make music",
    favoriteFood: "Sushi",
    favoriteVideoGame: "Call of duty",
    favoriteFilm: "American Psycho",
    favoriteBook: 'American Psycho',
    petName: 'Sasha'},
    {
        name: "Antonino",
        surname: "Alampi",
        age: 23,
        city: "Reggio di Calabria",
        hobby: "",
        favoriteFood: "Sushi",
        favoriteVideoGame: "Dark Souls",
        favoriteFilm: "Harry Potter",
        favoriteBook: "",
        petName: ""
    },
  {
    name: "Simone",
    surname: "Sbrilli",
    age: "31",
    city: "Roma",
    hobby: "Bass player",
    favoriteFood: "Pizza",
    favoriteVideoGame: "Genshin Impact",
    favoriteFilm: "Neon Genesis Evangelion",
    favoriteBook: 'Game OF Thrones',
    petName: 'Dylan, Black, Lucky',
  },
];